from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addroomtype(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, addroomtype):
        addroomtype.setObjectName("addroomtype")
        addroomtype.resize(515, 281)
        self.centralwidget = QtWidgets.QWidget(addroomtype)
        self.centralwidget.setObjectName("centralwidget")
        self.roomtype = QtWidgets.QLineEdit(self.centralwidget)
        self.roomtype.setGeometry(QtCore.QRect(90, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName("roomtype")
        self.addroomtype_label = QtWidgets.QLabel(self.centralwidget)
        self.addroomtype_label.setGeometry(QtCore.QRect(130, 30, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.addroomtype_label.setFont(font)
        self.addroomtype_label.setObjectName("addroomtype_label")
        self.roomtypeadded_label = QtWidgets.QLabel(self.centralwidget)
        self.roomtypeadded_label.setGeometry(QtCore.QRect(30, 220, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtypeadded_label.setFont(font)
        self.roomtypeadded_label.setObjectName("roomtypeadded_label")
        self.maxguests = QtWidgets.QLineEdit(self.centralwidget)
        self.maxguests.setGeometry(QtCore.QRect(280, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.maxguests.setFont(font)
        self.maxguests.setObjectName("maxguests")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(150, 170, 101, 28))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(270, 170, 101, 28))
        self.back.setObjectName("back")
        self.roomtypepresent_label = QtWidgets.QLabel(self.centralwidget)
        self.roomtypepresent_label.setGeometry(QtCore.QRect(30, 220, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtypepresent_label.setFont(font)
        self.roomtypepresent_label.setObjectName("roomtypepresent_label")
        addroomtype.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addroomtype)
        self.statusbar.setObjectName("statusbar")
        addroomtype.setStatusBar(self.statusbar)

        self.retranslateUi(addroomtype)
        QtCore.QMetaObject.connectSlotsByName(addroomtype)

    def retranslateUi(self, addroomtype):
        _translate = QtCore.QCoreApplication.translate
        addroomtype.setWindowTitle(_translate("addroomtype", "MainWindow"))
        self.roomtype.setPlaceholderText(_translate("addroomtype", "Room Type"))
        self.addroomtype_label.setText(_translate("addroomtype", "Add Room Type"))
        self.roomtypeadded_label.setText(_translate("addroomtype", "Room Type Added!"))
        self.maxguests.setPlaceholderText(_translate("addroomtype", "Max Guests"))
        self.submit.setText(_translate("addroomtype", "Submit"))
        self.back.setText(_translate("addroomtype", "Cancel"))
        self.roomtypepresent_label.setText(_translate("addroomtype", "Room Type already Present!"))
