from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addroomlist(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, addroomlist):
        addroomlist.setObjectName("addroomlist")
        addroomlist.resize(515, 281)
        self.centralwidget = QtWidgets.QWidget(addroomlist)
        self.centralwidget.setObjectName("centralwidget")
        self.roomno = QtWidgets.QLineEdit(self.centralwidget)
        self.roomno.setGeometry(QtCore.QRect(90, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomno.setFont(font)
        self.roomno.setObjectName("roomno")
        self.roomtype = QtWidgets.QComboBox(self.centralwidget)
        self.roomtype.setGeometry(QtCore.QRect(280, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName("roomtype")
        self.roomtype.addItem("")
        self.addroomlist_label = QtWidgets.QLabel(self.centralwidget)
        self.addroomlist_label.setGeometry(QtCore.QRect(140, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.addroomlist_label.setFont(font)
        self.addroomlist_label.setObjectName("addroomlist_label")
        self.roomadded_label = QtWidgets.QLabel(self.centralwidget)
        self.roomadded_label.setGeometry(QtCore.QRect(30, 230, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomadded_label.setFont(font)
        self.roomadded_label.setObjectName("roomadded_label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(160, 170, 101, 28))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(280, 170, 101, 28))
        self.back.setObjectName("back")
        self.roompresent_label = QtWidgets.QLabel(self.centralwidget)
        self.roompresent_label.setGeometry(QtCore.QRect(30, 230, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roompresent_label.setFont(font)
        self.roompresent_label.setObjectName("roompresent_label")
        addroomlist.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addroomlist)
        self.statusbar.setObjectName("statusbar")
        addroomlist.setStatusBar(self.statusbar)

        self.retranslateUi(addroomlist)
        QtCore.QMetaObject.connectSlotsByName(addroomlist)

    def retranslateUi(self, addroomlist):
        _translate = QtCore.QCoreApplication.translate
        addroomlist.setWindowTitle(_translate("addroomlist", "MainWindow"))
        self.roomno.setPlaceholderText(_translate("addroomlist", "Room Number"))
        self.roomtype.setItemText(0, _translate("addroomlist", "Room Type"))
        self.addroomlist_label.setText(_translate("addroomlist", "Add Room List"))
        self.roomadded_label.setText(_translate("addroomlist", "Room Added!"))
        self.submit.setText(_translate("addroomlist", "Submit"))
        self.back.setText(_translate("addroomlist", "Cancel"))
        self.roompresent_label.setText(_translate("addroomlist", "Room Already Present!"))
