from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_delete_reservation(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, delete_reservation):
        delete_reservation.setObjectName("delete_reservation")
        delete_reservation.resize(516, 326)
        self.centralwidget = QtWidgets.QWidget(delete_reservation)
        self.centralwidget.setObjectName("centralwidget")
        self.deletereserve_label = QtWidgets.QLabel(self.centralwidget)
        self.deletereserve_label.setGeometry(QtCore.QRect(130, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.deletereserve_label.setFont(font)
        self.deletereserve_label.setObjectName("deletereserve_label")
        self.bookingsubmit = QtWidgets.QPushButton(self.centralwidget)
        self.bookingsubmit.setGeometry(QtCore.QRect(80, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.bookingsubmit.setFont(font)
        self.bookingsubmit.setObjectName("bookingsubmit")
        self.reservationdeleted_label = QtWidgets.QLabel(self.centralwidget)
        self.reservationdeleted_label.setEnabled(True)
        self.reservationdeleted_label.setGeometry(QtCore.QRect(20, 240, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reservationdeleted_label.setFont(font)
        self.reservationdeleted_label.setObjectName("reservationdeleted_label")
        self.bookingid_notfound_label = QtWidgets.QLabel(self.centralwidget)
        self.bookingid_notfound_label.setEnabled(True)
        self.bookingid_notfound_label.setGeometry(QtCore.QRect(20, 240, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookingid_notfound_label.setFont(font)
        self.bookingid_notfound_label.setObjectName("bookingid_notfound_label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(280, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.bookingid = QtWidgets.QLineEdit(self.centralwidget)
        self.bookingid.setGeometry(QtCore.QRect(130, 110, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookingid.setFont(font)
        self.bookingid.setObjectName("bookingid")
        delete_reservation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(delete_reservation)
        self.statusbar.setObjectName("statusbar")
        delete_reservation.setStatusBar(self.statusbar)

        self.retranslateUi(delete_reservation)
        QtCore.QMetaObject.connectSlotsByName(delete_reservation)

    def retranslateUi(self, delete_reservation):
        _translate = QtCore.QCoreApplication.translate
        delete_reservation.setWindowTitle(_translate("delete_reservation", "MainWindow"))
        self.deletereserve_label.setText(_translate("delete_reservation", "Delete Reservation"))
        self.bookingsubmit.setText(_translate("delete_reservation", "Submit"))
        self.reservationdeleted_label.setToolTip(_translate("delete_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.reservationdeleted_label.setWhatsThis(_translate("delete_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.reservationdeleted_label.setText(_translate("delete_reservation", "Reservation Deleted!"))
        self.bookingid_notfound_label.setToolTip(_translate("delete_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.bookingid_notfound_label.setWhatsThis(_translate("delete_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.bookingid_notfound_label.setText(_translate("delete_reservation", "Booking ID not Found!"))
        self.back.setText(_translate("delete_reservation", "Cancel"))
        self.bookingid.setPlaceholderText(_translate("delete_reservation", "                Booking Id"))
