from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_guest_list(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, guest_list):
        guest_list.setObjectName("guest_list")
        guest_list.resize(1003, 828)
        self.centralwidget = QtWidgets.QWidget(guest_list)
        self.centralwidget.setObjectName("centralwidget")
        self.guestlist_label = QtWidgets.QLabel(self.centralwidget)
        self.guestlist_label.setGeometry(QtCore.QRect(410, 30, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.guestlist_label.setFont(font)
        self.guestlist_label.setObjectName("guestlist_label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(530, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.guest_view = QtWidgets.QTableWidget(self.centralwidget)
        self.guest_view.setGeometry(QtCore.QRect(0, 250, 1001, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.guest_view.setFont(font)
        self.guest_view.setColumnCount(10)
        self.guest_view.setObjectName("guest_view")
        self.guest_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.guest_view.setHorizontalHeaderItem(9, item)
        self.guest_view.horizontalHeader().setDefaultSectionSize(200)
        self.resultsnotfound_label = QtWidgets.QLabel(self.centralwidget)
        self.resultsnotfound_label.setGeometry(QtCore.QRect(10, 220, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultsnotfound_label.setFont(font)
        self.resultsnotfound_label.setObjectName("resultsnotfound_label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(530, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.guestname = QtWidgets.QLineEdit(self.centralwidget)
        self.guestname.setGeometry(QtCore.QRect(270, 140, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.guestname.setFont(font)
        self.guestname.setText("")
        self.guestname.setObjectName("guestname")
        self.showall = QtWidgets.QPushButton(self.centralwidget)
        self.showall.setGeometry(QtCore.QRect(690, 140, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.showall.setFont(font)
        self.showall.setObjectName("showall")
        guest_list.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(guest_list)
        self.statusbar.setObjectName("statusbar")
        guest_list.setStatusBar(self.statusbar)

        self.retranslateUi(guest_list)
        QtCore.QMetaObject.connectSlotsByName(guest_list)

    def retranslateUi(self, guest_list):
        _translate = QtCore.QCoreApplication.translate
        guest_list.setWindowTitle(_translate("guest_list", "MainWindow"))
        self.guestlist_label.setText(_translate("guest_list", "Guest List"))
        self.submit.setText(_translate("guest_list", "Submit"))
        item = self.guest_view.horizontalHeaderItem(0)
        item.setText(_translate("guest_list", "Guest ID"))
        item = self.guest_view.horizontalHeaderItem(1)
        item.setText(_translate("guest_list", "Guest Name"))
        item = self.guest_view.horizontalHeaderItem(2)
        item.setText(_translate("guest_list", "Birthday"))
        item = self.guest_view.horizontalHeaderItem(3)
        item.setText(_translate("guest_list", "Phone"))
        item = self.guest_view.horizontalHeaderItem(4)
        item.setText(_translate("guest_list", "Email"))
        item = self.guest_view.horizontalHeaderItem(5)
        item.setText(_translate("guest_list", "Address"))
        item = self.guest_view.horizontalHeaderItem(6)
        item.setText(_translate("guest_list", "Room Number"))
        item = self.guest_view.horizontalHeaderItem(7)
        item.setText(_translate("guest_list", "Check In Date"))
        item = self.guest_view.horizontalHeaderItem(8)
        item.setText(_translate("guest_list", "Check Out Date"))
        item = self.guest_view.horizontalHeaderItem(9)
        item.setText(_translate("guest_list", "Status"))
        self.resultsnotfound_label.setText(_translate("guest_list", "No Results Found!"))
        self.back.setText(_translate("guest_list", "Back"))
        self.guestname.setPlaceholderText(_translate("guest_list", "Guest Name"))
        self.showall.setText(_translate("guest_list", "Show All"))
