from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_make_reservation(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, make_reservation):
        make_reservation.setObjectName("make_reservation")
        make_reservation.resize(515, 744)
        font = QtGui.QFont()
        font.setPointSize(6)
        make_reservation.setFont(font)
        make_reservation.setStatusTip("")
        make_reservation.setAccessibleDescription("")
        self.centralwidget = QtWidgets.QWidget(make_reservation)
        self.centralwidget.setObjectName("centralwidget")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(80, 690, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(50, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.birthday_label = QtWidgets.QLabel(self.centralwidget)
        self.birthday_label.setGeometry(QtCore.QRect(50, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.birthday_label.setFont(font)
        self.birthday_label.setObjectName("birthday_label")
        self.makereservation_lable = QtWidgets.QLabel(self.centralwidget)
        self.makereservation_lable.setGeometry(QtCore.QRect(140, 30, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.makereservation_lable.setFont(font)
        self.makereservation_lable.setObjectName("makereservation_lable")
        self.birthday = QtWidgets.QDateEdit(self.centralwidget)
        self.birthday.setGeometry(QtCore.QRect(50, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.birthday.setFont(font)
        self.birthday.setCalendarPopup(True)
        self.birthday.setObjectName("birthday")
        self.gender_label = QtWidgets.QLabel(self.centralwidget)
        self.gender_label.setGeometry(QtCore.QRect(190, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gender_label.setFont(font)
        self.gender_label.setObjectName("gender_label")
        self.gender = QtWidgets.QComboBox(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(190, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gender.setFont(font)
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.phone_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_label.setGeometry(QtCore.QRect(340, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.phone_label.setFont(font)
        self.phone_label.setObjectName("phone_label")
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(50, 230, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.email_label.setFont(font)
        self.email_label.setObjectName("email_label")
        self.address_label = QtWidgets.QLabel(self.centralwidget)
        self.address_label.setGeometry(QtCore.QRect(50, 310, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.address_label.setFont(font)
        self.address_label.setObjectName("address_label")
        self.state = QtWidgets.QComboBox(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(50, 440, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.state.setFont(font)
        self.state.setObjectName("state")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.state.addItem("")
        self.reservationinfo_label = QtWidgets.QLabel(self.centralwidget)
        self.reservationinfo_label.setGeometry(QtCore.QRect(50, 490, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.reservationinfo_label.setFont(font)
        self.reservationinfo_label.setObjectName("reservationinfo_label")
        self.guests = QtWidgets.QComboBox(self.centralwidget)
        self.guests.setGeometry(QtCore.QRect(50, 520, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.guests.setFont(font)
        self.guests.setObjectName("guests")
        self.guests.addItem("")
        self.guests.addItem("")
        self.guests.addItem("")
        self.guests.addItem("")
        self.guests.addItem("")
        self.roomtype = QtWidgets.QComboBox(self.centralwidget)
        self.roomtype.setGeometry(QtCore.QRect(230, 520, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName("roomtype")
        self.roomtype.addItem("")
        self.checkin = QtWidgets.QDateEdit(self.centralwidget)
        self.checkin.setGeometry(QtCore.QRect(50, 600, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkin.setFont(font)
        self.checkin.setCalendarPopup(True)
        self.checkin.setObjectName("checkin")
        self.checkin_label = QtWidgets.QLabel(self.centralwidget)
        self.checkin_label.setGeometry(QtCore.QRect(50, 570, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkin_label.setFont(font)
        self.checkin_label.setObjectName("checkin_label")
        self.checkout = QtWidgets.QDateEdit(self.centralwidget)
        self.checkout.setGeometry(QtCore.QRect(230, 600, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkout.setFont(font)
        self.checkout.setCalendarPopup(True)
        self.checkout.setObjectName("checkout")
        self.checkout_label = QtWidgets.QLabel(self.centralwidget)
        self.checkout_label.setGeometry(QtCore.QRect(230, 570, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkout_label.setFont(font)
        self.checkout_label.setObjectName("checkout_label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(270, 690, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.fname = QtWidgets.QLineEdit(self.centralwidget)
        self.fname.setGeometry(QtCore.QRect(50, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.fname.setFont(font)
        self.fname.setObjectName("fname")
        self.mname = QtWidgets.QLineEdit(self.centralwidget)
        self.mname.setGeometry(QtCore.QRect(190, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.mname.setFont(font)
        self.mname.setObjectName("mname")
        self.lname = QtWidgets.QLineEdit(self.centralwidget)
        self.lname.setGeometry(QtCore.QRect(340, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lname.setFont(font)
        self.lname.setObjectName("lname")
        self.phone = QtWidgets.QLineEdit(self.centralwidget)
        self.phone.setGeometry(QtCore.QRect(340, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.phone.setFont(font)
        self.phone.setObjectName("phone")
        self.email = QtWidgets.QLineEdit(self.centralwidget)
        self.email.setGeometry(QtCore.QRect(50, 260, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.email.setFont(font)
        self.email.setObjectName("email")
        self.buildingno = QtWidgets.QLineEdit(self.centralwidget)
        self.buildingno.setGeometry(QtCore.QRect(50, 340, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buildingno.setFont(font)
        self.buildingno.setObjectName("buildingno")
        self.locality = QtWidgets.QLineEdit(self.centralwidget)
        self.locality.setGeometry(QtCore.QRect(270, 340, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.locality.setFont(font)
        self.locality.setObjectName("locality")
        self.city = QtWidgets.QLineEdit(self.centralwidget)
        self.city.setGeometry(QtCore.QRect(270, 390, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.city.setFont(font)
        self.city.setObjectName("city")
        self.street = QtWidgets.QLineEdit(self.centralwidget)
        self.street.setGeometry(QtCore.QRect(50, 390, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.street.setFont(font)
        self.street.setObjectName("street")
        self.pincode = QtWidgets.QLineEdit(self.centralwidget)
        self.pincode.setGeometry(QtCore.QRect(270, 440, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pincode.setFont(font)
        self.pincode.setObjectName("pincode")
        self.infoinvalid_label = QtWidgets.QLabel(self.centralwidget)
        self.infoinvalid_label.setGeometry(QtCore.QRect(30, 650, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.infoinvalid_label.setFont(font)
        self.infoinvalid_label.setObjectName("infoinvalid_label")
        make_reservation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(make_reservation)
        self.statusbar.setObjectName("statusbar")
        make_reservation.setStatusBar(self.statusbar)

        self.retranslateUi(make_reservation)
        QtCore.QMetaObject.connectSlotsByName(make_reservation)
        make_reservation.setTabOrder(self.birthday, self.gender)
        make_reservation.setTabOrder(self.gender, self.submit)

    def retranslateUi(self, make_reservation):
        _translate = QtCore.QCoreApplication.translate
        make_reservation.setWindowTitle(_translate("make_reservation", "MainWindow"))
        self.submit.setText(_translate("make_reservation", "Submit"))
        self.name_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.name_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.name_label.setText(_translate("make_reservation", "Name"))
        self.birthday_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.birthday_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.birthday_label.setText(_translate("make_reservation", "Birthday"))
        self.makereservation_lable.setText(_translate("make_reservation", "Make Reservation"))
        self.gender_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.gender_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.gender_label.setText(_translate("make_reservation", "Gender"))
        self.gender.setItemText(0, _translate("make_reservation", "M"))
        self.gender.setItemText(1, _translate("make_reservation", "F"))
        self.phone_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.phone_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.phone_label.setText(_translate("make_reservation", "Phone"))
        self.email_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.email_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.email_label.setText(_translate("make_reservation", "E-Mail"))
        self.address_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.address_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.address_label.setText(_translate("make_reservation", "Address"))
        self.state.setPlaceholderText(_translate("make_reservation", "State"))
        self.state.setItemText(0, _translate("make_reservation", "State"))
        self.state.setItemText(1, _translate("make_reservation", "Andhra Pradesh"))
        self.state.setItemText(2, _translate("make_reservation", "Arunachal Pradesh"))
        self.state.setItemText(3, _translate("make_reservation", "Bihar"))
        self.state.setItemText(4, _translate("make_reservation", "Chhattisgarh"))
        self.state.setItemText(5, _translate("make_reservation", "Delhi"))
        self.state.setItemText(6, _translate("make_reservation", "Goa"))
        self.state.setItemText(7, _translate("make_reservation", "Gujarat"))
        self.state.setItemText(8, _translate("make_reservation", "Haryana"))
        self.state.setItemText(9, _translate("make_reservation", "Himachal Pradesh"))
        self.state.setItemText(10, _translate("make_reservation", "Jharkhand"))
        self.state.setItemText(11, _translate("make_reservation", "Karnataka"))
        self.state.setItemText(12, _translate("make_reservation", "Kerala"))
        self.state.setItemText(13, _translate("make_reservation", "Assam"))
        self.state.setItemText(14, _translate("make_reservation", "Madhya Pradesh"))
        self.state.setItemText(15, _translate("make_reservation", "Maharashtra"))
        self.state.setItemText(16, _translate("make_reservation", "Manipur"))
        self.state.setItemText(17, _translate("make_reservation", "Meghalaya"))
        self.state.setItemText(18, _translate("make_reservation", "Mizoram"))
        self.state.setItemText(19, _translate("make_reservation", "Nagaland"))
        self.state.setItemText(20, _translate("make_reservation", "Odisha"))
        self.state.setItemText(21, _translate("make_reservation", "Punjab"))
        self.state.setItemText(22, _translate("make_reservation", "Rajasthan"))
        self.state.setItemText(23, _translate("make_reservation", "Sikkim"))
        self.state.setItemText(24, _translate("make_reservation", "Tamil Nadu"))
        self.state.setItemText(25, _translate("make_reservation", "Telangana"))
        self.state.setItemText(26, _translate("make_reservation", "Tripura"))
        self.state.setItemText(27, _translate("make_reservation", "Uttarakhand"))
        self.state.setItemText(28, _translate("make_reservation", "Uttar Pradesh"))
        self.state.setItemText(29, _translate("make_reservation", "West Bengal"))
        self.reservationinfo_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.reservationinfo_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.reservationinfo_label.setText(_translate("make_reservation", "Reservation Info"))
        self.guests.setPlaceholderText(_translate("make_reservation", "Number of People"))
        self.guests.setItemText(0, _translate("make_reservation", "Number of People"))
        self.guests.setItemText(1, _translate("make_reservation", "1"))
        self.guests.setItemText(2, _translate("make_reservation", "2"))
        self.guests.setItemText(3, _translate("make_reservation", "3"))
        self.guests.setItemText(4, _translate("make_reservation", "4"))
        self.roomtype.setPlaceholderText(_translate("make_reservation", "Room Type"))
        self.roomtype.setItemText(0, _translate("make_reservation", "Room Type"))
        self.checkin_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.checkin_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.checkin_label.setText(_translate("make_reservation", "Check In "))
        self.checkout_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.checkout_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.checkout_label.setText(_translate("make_reservation", "Check Out "))
        self.back.setText(_translate("make_reservation", "Cancel"))
        self.fname.setPlaceholderText(_translate("make_reservation", "First Name"))
        self.mname.setPlaceholderText(_translate("make_reservation", "Middle Name"))
        self.lname.setPlaceholderText(_translate("make_reservation", "Last Name"))
        self.phone.setPlaceholderText(_translate("make_reservation", "xxxxxxxxxx"))
        self.email.setPlaceholderText(_translate("make_reservation", "example@mail.com"))
        self.buildingno.setPlaceholderText(_translate("make_reservation", "Building Number"))
        self.locality.setPlaceholderText(_translate("make_reservation", "Locality"))
        self.city.setPlaceholderText(_translate("make_reservation", "City"))
        self.street.setPlaceholderText(_translate("make_reservation", "Street"))
        self.pincode.setPlaceholderText(_translate("make_reservation", "Zip Code"))
        self.infoinvalid_label.setToolTip(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.infoinvalid_label.setWhatsThis(_translate("make_reservation", "<html><head/><body><p>Name</p></body></html>"))
        self.infoinvalid_label.setText(_translate("make_reservation", "One or more Fields Empty or Invalid!"))
