from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_removeroom(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, removeroom):
        removeroom.setObjectName("removeroom")
        removeroom.resize(515, 323)
        self.centralwidget = QtWidgets.QWidget(removeroom)
        self.centralwidget.setObjectName("centralwidget")
        self.removeroom_label = QtWidgets.QLabel(self.centralwidget)
        self.removeroom_label.setGeometry(QtCore.QRect(140, 30, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.removeroom_label.setFont(font)
        self.removeroom_label.setObjectName("removeroom_label")
        self.roomremoved_label = QtWidgets.QLabel(self.centralwidget)
        self.roomremoved_label.setGeometry(QtCore.QRect(30, 240, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomremoved_label.setFont(font)
        self.roomremoved_label.setObjectName("roomremoved_label")
        self.roomno = QtWidgets.QComboBox(self.centralwidget)
        self.roomno.setGeometry(QtCore.QRect(180, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomno.setFont(font)
        self.roomno.setObjectName("roomno")
        self.roomno.addItem("")
        self.pleaseselectroomno_label = QtWidgets.QLabel(self.centralwidget)
        self.pleaseselectroomno_label.setGeometry(QtCore.QRect(30, 240, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pleaseselectroomno_label.setFont(font)
        self.pleaseselectroomno_label.setObjectName("pleaseselectroomno_label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(140, 170, 101, 28))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(260, 170, 101, 28))
        self.back.setObjectName("back")
        self.roomisoccupied_label = QtWidgets.QLabel(self.centralwidget)
        self.roomisoccupied_label.setGeometry(QtCore.QRect(30, 240, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomisoccupied_label.setFont(font)
        self.roomisoccupied_label.setObjectName("roomisoccupied_label")
        removeroom.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(removeroom)
        self.statusbar.setObjectName("statusbar")
        removeroom.setStatusBar(self.statusbar)

        self.retranslateUi(removeroom)
        QtCore.QMetaObject.connectSlotsByName(removeroom)

    def retranslateUi(self, removeroom):
        _translate = QtCore.QCoreApplication.translate
        removeroom.setWindowTitle(_translate("removeroom", "MainWindow"))
        self.removeroom_label.setText(_translate("removeroom", "Remove Room"))
        self.roomremoved_label.setText(_translate("removeroom", "Room Removed!"))
        self.roomno.setItemText(0, _translate("removeroom", "Room Number"))
        self.pleaseselectroomno_label.setText(_translate("removeroom", "Please Select Room No.!"))
        self.submit.setText(_translate("removeroom", "Submit"))
        self.back.setText(_translate("removeroom", "Cancel"))
        self.roomisoccupied_label.setText(_translate("removeroom", "Cannot Remove Room as Room is Occupied!"))
