from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_removeroomtype(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, removeroomtype):
        removeroomtype.setObjectName("removeroomtype")
        removeroomtype.resize(515, 323)
        self.centralwidget = QtWidgets.QWidget(removeroomtype)
        self.centralwidget.setObjectName("centralwidget")
        self.removeroomtype_label = QtWidgets.QLabel(self.centralwidget)
        self.removeroomtype_label.setGeometry(QtCore.QRect(90, 30, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.removeroomtype_label.setFont(font)
        self.removeroomtype_label.setObjectName("removeroomtype_label")
        self.roomtyperemoved_label = QtWidgets.QLabel(self.centralwidget)
        self.roomtyperemoved_label.setGeometry(QtCore.QRect(30, 240, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtyperemoved_label.setFont(font)
        self.roomtyperemoved_label.setObjectName("roomtyperemoved_label")
        self.roomtype = QtWidgets.QComboBox(self.centralwidget)
        self.roomtype.setGeometry(QtCore.QRect(180, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roomtype.setFont(font)
        self.roomtype.setObjectName("roomtype")
        self.roomtype.addItem("")
        self.pleaseselectroomtype_label = QtWidgets.QLabel(self.centralwidget)
        self.pleaseselectroomtype_label.setGeometry(QtCore.QRect(30, 240, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pleaseselectroomtype_label.setFont(font)
        self.pleaseselectroomtype_label.setObjectName("pleaseselectroomtype_label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(150, 170, 101, 28))
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(270, 170, 101, 28))
        self.back.setObjectName("back")
        self.roomtypeisoccupied_label = QtWidgets.QLabel(self.centralwidget)
        self.roomtypeisoccupied_label.setGeometry(QtCore.QRect(30, 240, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.roomtypeisoccupied_label.setFont(font)
        self.roomtypeisoccupied_label.setObjectName("roomtypeisoccupied_label")
        removeroomtype.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(removeroomtype)
        self.statusbar.setObjectName("statusbar")
        removeroomtype.setStatusBar(self.statusbar)

        self.retranslateUi(removeroomtype)
        QtCore.QMetaObject.connectSlotsByName(removeroomtype)

    def retranslateUi(self, removeroomtype):
        _translate = QtCore.QCoreApplication.translate
        removeroomtype.setWindowTitle(_translate("removeroomtype", "MainWindow"))
        self.removeroomtype_label.setText(_translate("removeroomtype", "Remove Room Type"))
        self.roomtyperemoved_label.setText(_translate("removeroomtype", "Room Type Removed!"))
        self.roomtype.setItemText(0, _translate("removeroomtype", "Room Type"))
        self.pleaseselectroomtype_label.setText(_translate("removeroomtype", "Please Select Room Type!"))
        self.submit.setText(_translate("removeroomtype", "Submit"))
        self.back.setText(_translate("removeroomtype", "Cancel"))
        self.roomtypeisoccupied_label.setText(_translate("removeroomtype", "Cannot Remove Room Type as Rooms are Occupied!"))
