from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_search_reservation(object):
    def __init__(self):
        self.setupUi(self)
        
    def setupUi(self, search_reservation):
        search_reservation.setObjectName("search_reservation")
        search_reservation.resize(1003, 828)
        self.centralwidget = QtWidgets.QWidget(search_reservation)
        self.centralwidget.setObjectName("centralwidget")
        self.search_reservation_label = QtWidgets.QLabel(self.centralwidget)
        self.search_reservation_label.setGeometry(QtCore.QRect(360, 30, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.search_reservation_label.setFont(font)
        self.search_reservation_label.setObjectName("search_reservation_label")
        self.from_date = QtWidgets.QDateEdit(self.centralwidget)
        self.from_date.setGeometry(QtCore.QRect(90, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.from_date.setFont(font)
        self.from_date.setCalendarPopup(True)
        self.from_date.setObjectName("from_date")
        self.from_label = QtWidgets.QLabel(self.centralwidget)
        self.from_label.setGeometry(QtCore.QRect(90, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.to_date = QtWidgets.QDateEdit(self.centralwidget)
        self.to_date.setGeometry(QtCore.QRect(340, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.to_date.setFont(font)
        self.to_date.setCalendarPopup(True)
        self.to_date.setObjectName("to_date")
        self.to_label = QtWidgets.QLabel(self.centralwidget)
        self.to_label.setGeometry(QtCore.QRect(340, 110, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.to_label.setFont(font)
        self.to_label.setObjectName("to_label")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(590, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.search_view = QtWidgets.QTableWidget(self.centralwidget)
        self.search_view.setGeometry(QtCore.QRect(0, 250, 1001, 531))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.search_view.setFont(font)
        self.search_view.setColumnCount(11)
        self.search_view.setObjectName("search_view")
        self.search_view.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_view.setHorizontalHeaderItem(10, item)
        self.search_view.horizontalHeader().setDefaultSectionSize(200)
        self.resultsnotfound_label = QtWidgets.QLabel(self.centralwidget)
        self.resultsnotfound_label.setGeometry(QtCore.QRect(10, 220, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resultsnotfound_label.setFont(font)
        self.resultsnotfound_label.setObjectName("resultsnotfound_label")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(760, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back.setFont(font)
        self.back.setObjectName("back")
        search_reservation.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(search_reservation)
        self.statusbar.setObjectName("statusbar")
        search_reservation.setStatusBar(self.statusbar)

        self.retranslateUi(search_reservation)
        QtCore.QMetaObject.connectSlotsByName(search_reservation)

    def retranslateUi(self, search_reservation):
        _translate = QtCore.QCoreApplication.translate
        search_reservation.setWindowTitle(_translate("search_reservation", "MainWindow"))
        self.search_reservation_label.setText(_translate("search_reservation", "Search Reservation"))
        self.from_label.setText(_translate("search_reservation", "From:"))
        self.to_label.setText(_translate("search_reservation", "To:"))
        self.submit.setText(_translate("search_reservation", "Submit"))
        item = self.search_view.horizontalHeaderItem(0)
        item.setText(_translate("search_reservation", "Booking ID"))
        item = self.search_view.horizontalHeaderItem(1)
        item.setText(_translate("search_reservation", "Guest Name"))
        item = self.search_view.horizontalHeaderItem(2)
        item.setText(_translate("search_reservation", "Birthday"))
        item = self.search_view.horizontalHeaderItem(3)
        item.setText(_translate("search_reservation", "Phone"))
        item = self.search_view.horizontalHeaderItem(4)
        item.setText(_translate("search_reservation", "Email"))
        item = self.search_view.horizontalHeaderItem(5)
        item.setText(_translate("search_reservation", "Address"))
        item = self.search_view.horizontalHeaderItem(6)
        item.setText(_translate("search_reservation", "No. of People"))
        item = self.search_view.horizontalHeaderItem(7)
        item.setText(_translate("search_reservation", "Room Type "))
        item = self.search_view.horizontalHeaderItem(8)
        item.setText(_translate("search_reservation", "Check In Date"))
        item = self.search_view.horizontalHeaderItem(9)
        item.setText(_translate("search_reservation", "Check Out Date"))
        item = self.search_view.horizontalHeaderItem(10)
        item.setText(_translate("search_reservation", "Reservation Date"))
        self.resultsnotfound_label.setText(_translate("search_reservation", "No Results Found!"))
        self.back.setText(_translate("search_reservation", "Back"))
